language: java
dist: xenial

before_install:
 - sudo apt-get update
 - sudo apt-get install -y wget

before_script:
  - mkdir -p bin
  - export PATH=$PATH:$PWD/bin
  - wget https://github.com/owlcollab/owltools/releases/download/2020-04-06/owltools -O bin/owltools
  - wget https://github.com/owlcollab/owltools/releases/download/2020-04-06/owltools-oort-all.jar  -O bin/owltools-runner-all.jar 
  - chmod +x bin/*

# command to run tests
script: make travis-test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - cjmungall@lbl.gov

