PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
INSERT DATA 
{
GRAPH <http://model.geneontology.org/56aac7ad00000038> { <http://model.geneontology.org/56aac7ad00000038> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/56aac7ad00000079> { <http://model.geneontology.org/56aac7ad00000079> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5716c41300000119> { <http://model.geneontology.org/5716c41300000119> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5716c41300000127> { <http://model.geneontology.org/5716c41300000127> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5716c41300000223> { <http://model.geneontology.org/5716c41300000223> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5716c41300000258> { <http://model.geneontology.org/5716c41300000258> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5716c41300000277> { <http://model.geneontology.org/5716c41300000277> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5716c41300000321> { <http://model.geneontology.org/5716c41300000321> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5716c41300000389> { <http://model.geneontology.org/5716c41300000389> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5716c41300000422> { <http://model.geneontology.org/5716c41300000422> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5745387b00001254> { <http://model.geneontology.org/5745387b00001254> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5745387b00001308> { <http://model.geneontology.org/5745387b00001308> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5745387b00001376> { <http://model.geneontology.org/5745387b00001376> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5745387b00001459> { <http://model.geneontology.org/5745387b00001459> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5745387b00001502> { <http://model.geneontology.org/5745387b00001502> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5745387b00001516> { <http://model.geneontology.org/5745387b00001516> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5745387b00001648> { <http://model.geneontology.org/5745387b00001648> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5745387b00001665> { <http://model.geneontology.org/5745387b00001665> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5745387b00001874> { <http://model.geneontology.org/5745387b00001874> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/57c82fad00000403> { <http://model.geneontology.org/57c82fad00000403> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/57c82fad00000528> { <http://model.geneontology.org/57c82fad00000528> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/57c82fad00000585> { <http://model.geneontology.org/57c82fad00000585> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/57c82fad00000619> { <http://model.geneontology.org/57c82fad00000619> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/57c82fad00000639> { <http://model.geneontology.org/57c82fad00000639> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/57c82fad00000695> { <http://model.geneontology.org/57c82fad00000695> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/57c82fad00000784> { <http://model.geneontology.org/57c82fad00000784> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/57c82fad00000847> { <http://model.geneontology.org/57c82fad00000847> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/57ea2dae00000004> { <http://model.geneontology.org/57ea2dae00000004> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/57f1b14b00000173> { <http://model.geneontology.org/57f1b14b00000173> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/580e952200000046> { <http://model.geneontology.org/580e952200000046> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/581e072c00000295> { <http://model.geneontology.org/581e072c00000295> <http://purl.org/pav/providedBy> "http://www.xenbase.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5825564b00000099> { <http://model.geneontology.org/5825564b00000099> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5825564b00000175> { <http://model.geneontology.org/5825564b00000175> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5835403200000017> { <http://model.geneontology.org/5835403200000017> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/583f430000000002> { <http://model.geneontology.org/583f430000000002> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/584b49fa00000005> { <http://model.geneontology.org/584b49fa00000005> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/584b49fa00000309> { <http://model.geneontology.org/584b49fa00000309> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/584b49fa00000326> { <http://model.geneontology.org/584b49fa00000326> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/584b49fa00000366> { <http://model.geneontology.org/584b49fa00000366> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/584b49fa00000411> { <http://model.geneontology.org/584b49fa00000411> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/586fc17a00000000> { <http://model.geneontology.org/586fc17a00000000> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/586fc17a00000381> { <http://model.geneontology.org/586fc17a00000381> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/586fc17a00000482> { <http://model.geneontology.org/586fc17a00000482> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/586fc17a00000528> { <http://model.geneontology.org/586fc17a00000528> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/586fc17a00000616> { <http://model.geneontology.org/586fc17a00000616> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/586fc17a00000703> { <http://model.geneontology.org/586fc17a00000703> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/586fc17a00000705> { <http://model.geneontology.org/586fc17a00000705> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/586fc17a00000729> { <http://model.geneontology.org/586fc17a00000729> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/586fc17a00000791> { <http://model.geneontology.org/586fc17a00000791> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/586fc17a00001862> { <http://model.geneontology.org/586fc17a00001862> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5900dc7400000219> { <http://model.geneontology.org/5900dc7400000219> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5900dc7400000396> { <http://model.geneontology.org/5900dc7400000396> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5900dc7400000468> { <http://model.geneontology.org/5900dc7400000468> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5900dc7400000926> { <http://model.geneontology.org/5900dc7400000926> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5900dc7400000968> { <http://model.geneontology.org/5900dc7400000968> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5900dc7400001271> { <http://model.geneontology.org/5900dc7400001271> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/593423e000001001> { <http://model.geneontology.org/593423e000001001> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/593423e000001079> { <http://model.geneontology.org/593423e000001079> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5941cdbd00000284> { <http://model.geneontology.org/5941cdbd00000284> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5941cdbd00000352> { <http://model.geneontology.org/5941cdbd00000352> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
GRAPH <http://model.geneontology.org/5745387b00001770> { <http://model.geneontology.org/5745387b00001770> <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string . }
}