name: run-owltools-test
on: 
  push: 
   branches: [master, dev]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    types: trigger-run-tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-java@v2

      - name: Run tests
        run: |
	  make travis-test
