name: run-owltools-test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions/setup-java@v2

    # Excute the Makefile
    - name: Make All
      run: |
        make all
